In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

C:\Users\asus\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [2]:
dataset = pd.read_csv('Churn_Modelling.csv')

In [3]:
dataset.shape

(10000, 14)

In [4]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [35]:
X = dataset.iloc[:,3:-1]

In [36]:
pd.unique(X['Geography'])

array(['France', 'Spain', 'Germany'], dtype=object)

In [37]:
encoder = LabelEncoder()

In [38]:
X['Gender'] = encoder.fit_transform(X['Gender'])

In [39]:
X['Gender'].head(10)

0    0
1    0
2    0
3    0
4    0
5    1
6    1
7    0
8    1
9    1
Name: Gender, dtype: int32

In [40]:
X['Geography'] = encoder.fit_transform(X['Geography'])

In [41]:
X['Geography'].head(10)

0    0
1    2
2    0
3    0
4    2
5    2
6    0
7    1
8    0
9    0
Name: Geography, dtype: int32

In [42]:
X = X.drop('Geography', axis=1)

In [43]:
geog = dataset['Geography']

In [44]:
geog = encoder.fit_transform(geog)

In [45]:
onehot = OneHotEncoder()

In [46]:
geog = onehot.fit_transform(geog.reshape(-1,1)).toarray()

In [47]:
geog[:3]

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [48]:
X = X.values

In [49]:
X = np.c_[X,geog]

In [50]:
X[0]

array([6.1900000e+02, 0.0000000e+00, 4.2000000e+01, 2.0000000e+00,
       0.0000000e+00, 1.0000000e+00, 1.0000000e+00, 1.0000000e+00,
       1.0134888e+05, 1.0000000e+00, 0.0000000e+00, 0.0000000e+00])

In [51]:
y = dataset['Exited'].values

In [52]:
sc = StandardScaler()

In [53]:
X = sc.fit_transform(X)

In [54]:
y = sc.fit_transform(y.reshape(-1,1))

In [55]:
X[0]

array([-0.32622142, -1.09598752,  0.29351742, -1.04175968, -1.22584767,
       -0.91158349,  0.64609167,  0.97024255,  0.02188649,  0.99720391,
       -0.57873591, -0.57380915])

In [56]:
y[0]

array([1.97716468])